### ISSUE TITLE
Crash when continuing game on another character

### ISSUE THREAD

**Issue by StrangeOne101** [Singulariity/satorugojo-isaac#2]
# Description
When I continued a save on another character, a crash occurred

# Log.txt file
```
[INFO] - [C](-1): RemoveCollectible
[INFO] - ...s/satorugojo_3159985495/gojo_src/core/unlock_manager.lua(215): postPlayerInit
[INFO] - ...ugojo_3159985495/gojo_src/callbacks/post_player_init.lua(8): Function
[INFO] - resources/scripts/main.lua(73): ?
```

# Steps to replicate
1. Start a new run on a non-Gojo character
2. Exit the run
3. Click "Continue" on the main menu
4. See crash

# Enviroment
- [x] All mods disabled except Gojo and Giantbook & Achievement API
- [x] Latest Isaac version and mod version

**Comment by Singulariity** [comment]
Thank you! I'll fix it asap
